modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/cech12/BucketLib/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="bucketlib"
    version="${file.jarVersion}"
    displayName="BucketLib"
    displayURL="https://github.com/cech12/BucketLib"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A library mod for custom buckets.
    '''
#[[mods]]
#    modId="bucketlibtest"
#    version="${file.jarVersion}"
#    displayName="BucketLibTest"
#    displayURL="https://github.com/cech12/BucketLib"
#    logoFile="logo.png"
#    authors="Cech12"
#    description='''
#    A test mod for the BucketLib library mod.
#    '''
[[dependencies.bucketlib]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bucketlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bucketlib]]
   modId="jei"
   mandatory=false
   versionRange="[9.4.1.113,)"
   ordering="NONE"
   side="BOTH"