# This workflow builds the project on each push and pull request

name: CI-Workflow

on:
  push:
    branches: [ "1.18" ]
  pull_request:
    branches: [ "1.18" ]

jobs:
  build:
    name: Build
    uses: cech12/BucketLib/.github/workflows/build.yml@1.18
  codeql:
    needs: build
    name: CodeQL
    uses: cech12/BucketLib/.github/workflows/codeql-analysis.yml@1.18

